#! /usr/bin/bash

source ~/loonyfetch/loony.conf
dis="0C"
isConnected=0
end(){
	for ((i=0; i<=16 ; i++)) do
		echo [60C
	done
}
#num+=8			num-3
Connected(){
	isConnected=1

	dis=$(grep [A-Z] ~/loonyfetch/mirage | sed 's/\x1B\[[0-9;]*[a-zA-Z]//g' | awk -v num=0 '{num=0; for(i=1;i<=length($0);i++) \
		{if (substr($0,i,1)=="F" || substr($0,i,1)=="L") { print num-5; exit} else if (substr($0,i,1)=="\t") \
		{num+=6} else {num++}}}')
	[[ $dis -ge 25 ]] && dis+="C" || dis="25C"
	cat ~/loonyfetch/mirage
}

#clear
PUB_IP=$(echo "Public IP: "; dig +short +timeout=1 myip.opendns.com @resolver1.opendns.com -4 2> /dev/null) 
[[ $? -eq 0 ]] && Connected || (lolcat ~/loonyfetch/macle && echo [$(< ~/loonyfetch/macle wc -l)A[9999999D[1m)

DATE=$(date)
echo [25A[9999999D[1m[$dis[4m$DATE[24m

NAME=$(echo -n $(whoami)@$(echo $HOSTNAME) $(tty | cut -d"/" -f3-))
echo [$dis$NAME"[0m"

RAM=$(free | awk '/Mem/ {print "Free Memory:",($7/$2)*100"%"}' && free -h | awk '/Mem/ {print " ---- " $7"/"$2}')
echo [$dis$RAM

DISK=$(df -h 2>/dev/null | awk '/\/$/ {print "Used Space: " $5 " ---- " $3"/"$2}')
echo [$dis$DISK

UP=$(uptime -p | sed -e 's/up/Uptime:/')
echo [$dis$UP

BAT=$(cat /sys/class/power_supply/BAT0/capacity | awk '{print("Battery Level: " $1 "%")}' && [[ $(cat /sys/class/power_supply/AC/online) == 1 ]] && echo "🗲" )
echo [$dis$BAT

#PRI_IP=$(ip -br a | grep 'UP' | awk '{print "Private IP: " $3}' )
PRI_IP=$(ip -br a | grep 'UP' | awk '{print "Private IP: " $3" "$4 }' )
echo [$dis$PRI_IP

[[ $location != "NULL" && isConnected -eq 1 ]] && WEATHER=$(curl -s wttr.in/$location?format=4 | sed 's/+/ /g')
[[ isConnected -eq 1 ]] && echo [$dis$PUB_IP && echo [$dis$WEATHER

end
echo [?25h[?7h
